services:
  db_pg_15:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: route_optimizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
